pipeline {
    agent any
    tools {
        jdk "JDK17"
        maven "MAVEN"
    }

    environment {
        cluster = "lojuvproappprod"
        service = "vprofileapptask-service-prod"
    }

    stages {
        stage('Deploy to Staging') {
            steps {
                script {
                    withAWS(credentials: 'awscreds', region: 'us-east-1') {
                        sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                    }
                }    
            }
        }
    }
}